### ISSUE TITLE
Garbled playing instructions on title screen

### ISSUE THREAD

**Issue by r-moeritz** [darrenfoulds/1nvader-c64#1]
Hi Darren,

first of all, thanks so much for making the source code to this game available. I'm a n00b to 6502 assembly programming and I feel that 1nvader is small enough to easily study and learn from (it's also damn good fun with a friend!). Anyway, on to my issues: when I assemble the sources with TMPx, I've noticed a few differences to the included PRG:

1. The starting address is $4000, so you have to `LOAD"*",8,1` followed by `SYS16384`. I don't mind, but it is quite different to the pre-assembled PRG, which includes a BASIC loader, so a `LOAD"*",8` followed by `RUN` works. Did you decide to omit the BASIC loader from the published source code to keep it simple / make it easier to study?
2. The pre-assembled PRG has scrolling text with playing instructions on the title screen: "Press fire to play", etc. When I assemble with TMPx, I get a string of unintelligable PETSCII chars instead, see attached screenshot. Am I missing an additional required step after assembling, such as crunching with exomizer?
3. The published source code does seem to be quite different to the pre-assembled PRG. For example, when I load the pre-assembled PRG, and search for the instruction `STA $D020  ; BORDER COLOUR` in Super Snapshot V5 using the "hunt" command (`H 0801 14D1 8D 20 D0`) it can't be found anywhere. Ditto other instructions I've searched for.

Alright, sorry for making this issue so long, and thanks again for publishing this great little game for all us lamers to study and enjoy! :)

![1nvader-garbled-instructions-titlescr](https://user-images.githubusercontent.com/426109/66700715-044f6c00-ecf4-11e9-9172-c47aa6dc2cff.png)

Regards,
Ralph

**Comment by darrenfoulds** [comment]
Hi Ralph,

Thanks for the email. I'm not ignoring you, and I will get back to you with
more information. 😀

I can answer a couple of your questions right now...

1. The downloadable .prg was created with one of those
cruncher/auto-runners (it may have been exomizer, Robin did that for me.)
So yes, taking a look at memory with that loaded will be different from the
source on GitHub.

2. It looks like the scroll text is in the wrong case. In fact, the source
on GitHub is just a dump and passing the PETSCII through ASCII and whatever
other encodings it went through before getting to GitHub probably switched
the case. Find the text near the end of the source and change it to
lowercase and you'll be set.

I should put up a version of the source that is in lowercase because that
works best with TMPx. Thanks for letting me know of the problems you are
having, I hope this helps to make things a bit clearer and that it helps in
your learning. 😀

D

[image: DarrenTheFoulds] <http://www.darrenfoulds.com/>

www.DarrenFoulds.com <https://www.darrenfoulds.com/>

🎙 Comfortable Place on the Couch <https://darrenfoulds.com/podcasts>
🐦 @darrenthefoulds <https://twitter.com/darrenthefoulds>

**Comment by r-moeritz** [comment]
Hi Darren, thanks for clarifying.

Cheers,
Ralph
